Allow REs longer than 4095 characters instead of skipping them
    ERROR: Skipping regular expression. Larger than 4095 characters:...

Until we find (and this time document!) a specific reason to
artificially restrict individual RE length, let the Squid configuration
tokenizer and the regex library limit REs. KISS.

After this specific change:

1. Squid continues to skip REs rejected by the regex library but, with
   longer REs now reaching regcomp(), the number of library rejections
   and the corresponding ERROR messages might[^1] go up.

2. Squid may silently start using previously skipped long REs.

3. Squid may fail/succeed/change RE optimization because the previously
   skipped long REs will now participate in optimization attempts.

[^1]: New rejections by the library based on the regex length is
unlikely in this context because libraries ought to accept much longer
regexes than longest Squid configuration tokens. For example, glibc
accepts 4MB-long regexes on 32-bit systems AFAICT from their code.