Fix support for test-suite/squidconf directive parameter files
Those files were never found. 2022 commit d37a3744 probably missed this
bug because the corresponding `squid -k parse` failures (quoted below)
do not result in non-zero exit status code. That failure handling
problem deserves a dedicated fix.

    ERROR: Can not open file empty.conf for reading
        configuration context: ./squidconf/regressions-3.4.0.1.conf(27)

----

Cherry-picked OT commit 04abbe9a and commit 39b270e7 changes from
SQUID-1064-make-configuration-includes-quoted-values-a-preprocessor-instruction-bag0
(a.k.a. commit 70014ef6).