fixup: Fix Mgr::StoreToCommWriter ctor pure virtual calls
    FATAL: Dying from an exception handling failure;
    exception: [no active exception]

    in OnTerminate () at main.cc:1310
    in std::terminate() () from libstdc++.so.6
    in __cxa_pure_virtual () from libstdc++.so.6
    in CbcPointer<Mgr::StoreToCommWriter>::CbcPointer at CbcPointer.h:94
    in Mgr::StoreToCommWriter::StoreToCommWriter at ...oCommWriter.cc:29

Earlier branch commit removed conflicting CBDATA_CLASS() calls from four
classes. Thankfully, that removal broke CI tests. The classes use call
toCbdata() from their constructors and that method became pure with
CBDATA_CLASS() removal.

We now use lighter CBDATA_INTERMEDIATE() instead. The code is as risky
as it used to be, but we are removing confusing/unused new/delete
operators from those intermediate classes and are better marking this
(old) cbdata problem.