Bug 5045: ext_edirectory_userip_acl is missing include files (#624)
Discovered on FreeBSD v12.1 running on amd64 with clang v8.0.1.

    error: use of undeclared identifier 'AF_INET6'
    error: member access into incomplete type 'struct sockaddr_in6'
    ...

Co-Authored-By: Pavel Timofeev <timp87@gmail.com>