Fix FTBFS due to -Werror=alloc-size-larger-than on GCC 12
GCC 12 emits an error when compiling squid due to
-Werror=alloc-size-larger-than.  The error looks like this:

store/Disks.cc:690:64: error: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
  690 |         const auto tmp = new SwapDir::Pointer[swap->n_allocated];
      |                                                                ^

Arguably, this is likely a compiler bug and not squid's fault.  Either
way, I believe it's worth having more type safety in this code.

Signed-off-by: Sergio Durigan Junior <sergiodj@sergiodj.net>