Fix (wrong) clang v4 HttpHeader.cc warning enabled by the -Wall option
    HttpHeader.cc:79:5: error: suggest braces around initialization of
    subobject [-Wmissing-braces]

The warning itself is a clang problem fixed in clang v6:
https://bugs.llvm.org/show_bug.cgi?id=21629

The "extra" pair of braces around the whole array initialization
expression in this fix is required (at least for GCC); see
https://stackoverflow.com/a/62252088