Revert "Undo introduction of references to metaHeaders() iteration"
    error: loop variable creates a copy [-Werror=range-loop-construct]

Looks like we cannot easily protect ourselves from notes modification.
That is not a big deal because such modification is unlikely.

This reverts previous branch commit 33c0fba.