Avoid making copies within for loops.
--

Previously, higher versions of clang would cause an error on
compiling Squid with -Wrange-loop-construct:

DestinationIp.cc:70:25: error: loop variable 'ip' creates
a copy from type 'const Ip::Address'
        for (const auto ip: ia->goodAndBad()) {

Asn.cc:598:25: error: loop variable 'ip' creates a copy from
type 'const Ip::Address'
        for (const auto ip: ia->goodAndBad()) {