fixup: Improve build with clang and modern GCC
    AsyncCallbacks.h:93:66: error: call to function 'operator<<' that is
    neither visible in the template definition nor found by
    argument-dependent lookup

This commit essentially reverses branch commit 7ca79b4 (fixup: Fixed
Ipc::StartListeningAnswer printing). I got the best location for
stand-alone function declarations wrong in that commit. The best
location for a function with an argument type from namespace X is,
naturally(?), inside that namespace X because it makes ADL work. Without
ADL, we would have to, for example, always #include ipc/StartListening.h
before #including base/AsyncCallbacks.h, which is problematic, on many
levels.

My GCC v10.3 is too forgiving about this problem in template lookups:
https://clang.llvm.org/compatibility.html#dep_lookup