Various patches from Pawel Worach
[patch] make trans. ipfilter compile
	one else too many?

[patch] update .cvsignore files
	Make all .cvsignore files up-to-date and add some
new ones to libTrie.

[patch] make ntlm_auth compile on freebsd 5.x
	I have no idea how portable this is but freebsd doesn't
use malloc.h anymore.

# grep error /usr/include/malloc.h
#error "<malloc.h> has been replaced by <stdlib.h>"

[patch] make auth_ntlm compile if NTLM_FAIL_OPEN is defined
	ntlm/auth_ntlm.cc: In function `stateful_helper_callback_t
   authenticateNTLMHandleReply(void*, void*, char*)':
ntlm/auth_ntlm.cc:601: error: invalid conversion from `void*' to `
   ntlm_helper_state_t*'

[patch] make useragent and referer log stuff compile
	Can't use class RefCount where a bool is expected says gcc 3.3.1
I guess this is the right fix :)

[patch] pam_auth has to be installed setuid root
	pam_auth has to be setuid root for it to work.
this could apply to 2.5 too.