Bug 5343: Fix GCC v14 build
    Reply.cc:198: error: no matching function for call to find(...)

The required STL header was missed in 2023 commit 27c3677 that updated
src/helper/Reply.cc.