Removed pconn-banger for similar reasons
The tool lacked build rules since inception (1997 commit eb5f55b) and
probably could not be built manually since at least 2007 commit cc192b5:

    pconn-banger.c:54:20: error: initializer element is not computable at load time
    #define PROXY_PORT "3128"

    pconn-banger.c:60:25: note: in expansion of macro ‘PROXY_PORT’
    static int proxy_port = PROXY_PORT;