Place more messages under cache_log_message control
XXX: Breaks build because various tools use libip w/o access to Config:

    debug/Messages.h:84: undefined reference to `Config'
    make[3]: *** [Makefile:946: squidclient] Error 1

    debug/Messages.h:84: undefined reference to `Config'
    make[2]: *** [Makefile:964: cachemgr.cgi] Error 1