Accept magic-only cache manager URLs
    ERROR: Squid BUG: assurance failed: tok.skip(internalMagicPrefix)
    exception location: cache_manager.cc(173) ParseUrl

Bad magic duplication led to Squid failing on magic-only cache manager
URLs that were rejected prior to commit 92a5adb. When the manager magic
constant was moved next to the internalStaticCheck(), it lost its
terminating slash -- mimicking its new neighbor: /squid-internal-static.

We could restore the slash, but it seems odd to require it, especially
since internal-static URL magic lacks it (TODO: Does it really?) and
typical origin server URLs do not require terminating slashes.

Also polished code to remove cache manager magic duplication and added
the corresponding unit tests.