Bug 5045: ext_edirectory_userip_acl is missing include files
    error: use of undeclared identifier 'AF_INET6'
    error: member access into incomplete type 'struct sockaddr_in6'
    ...

Discovered on FreeBSD 12.1 amd64 (clang-8.0.1).