Fix ./configure EUI check (#2338)
Fix missing header `sys/socket.h`:

    configure:29217: checking for struct arpreq.arp_pa
    .../net/if_arp.h: error: field has incomplete type 'struct sockaddr'

Fix `ac_aggr.arp_pa` test, replacing it with a test of a data member
that Squid code is actually using:

    conftest.cpp:112:5: error: value of type 'struct sockaddr' is not
        contextually convertible to 'bool'

Discovered while porting Squid v7 to FreeBSD.