Summary: Fixup remaining MSVC issues. Keywords:
Addresses -

protos.h:
c:\work\nt-3.0\src\protos.h(443) : warning C4190: '<Unknown>' has C-linkage
specified, but returns UDT 'String' which is incompatible with C
         c:\work\nt-3.0\src\squidstring.h(77) : see declaration of 'String'
c:\work\nt-3.0\src\protos.h(444) : warning C4190: '<Unknown>' has C-linkage
specified, but returns UDT 'String' which is incompatible with C
         c:\work\nt-3.0\src\squidstring.h(77) : see declaration of 'String'
c:\work\nt-3.0\src\protos.h(445) : warning C4190: '<Unknown>' has C-linkage
specified, but returns UDT 'String' which is incompatible with C
         c:\work\nt-3.0\src\squidstring.h(77) : see declaration of 'String'
c:\work\nt-3.0\src\protos.h(446) : warning C4190: '<Unknown>' has C-linkage
specified, but returns UDT 'String' which is incompatible with C
         c:\work\nt-3.0\src\squidstring.h(77) : see declaration of 'String'
c:\work\nt-3.0\src\protos.h(447) : warning C4190: '<Unknown>' has C-linkage
specified, but returns UDT 'String' which is incompatible with C
         c:\work\nt-3.0\src\squidstring.h(77) : see declaration of 'String'

protos.h:
c:\work\nt-3.0\src\protos.h(740) : error C2526: 'storeCreate' : C linkage
function cannot return C++ class 'RefCount<class storeIOState>'
c:\work\nt-3.0\src\protos.h(741) : error C2526: 'storeOpen' : C linkage
function cannot return C++ class 'RefCount<class storeIOState>'

typedefs.h:
c:\work\nt-3.0\src\httprequest.h(56) : warning C4099: 'HttpRequest' : type
name first seen using 'struct' now seen using 'class'
         c:\work\nt-3.0\src\typedefs.h(202) : see declaration of 'HttpRequest'

ACLRequestHeaderStrategy.h
c:\work\nt-3.0\src\aclrequestheaderstrategy.h(88) : error C2059: syntax
error : 'constant'

ACLStrategised.h
c:\work\nt-3.0\src\aclreplyheaderstrategy.h(88) : error C2059: syntax error
: 'constant'

ACLReplyHeaderStrategy.h:
c:\work\nt-3.0\src\aclreplyheaderstrategy.h(87) : error C2059: syntax error
: 'constant'