Do not use static initialization to register modules
    ERROR: ... Unknown authentication scheme 'ntlm'.

When module-provided names are never mentioned (directly or indirectly)
by main(), the linker may exclude the entire module code from the
executable.

For example, to the linker, code in src/auth/ntlm/ looks completely
unused because the linker does not know about the side effects of static
initialization that register an NtlmAuthRr object. When SquidMain()
later triggers the bootstrapConfig() event, that object calls
Auth::Scheme::AddScheme() with Auth::Ntlm::Scheme object to allow Squid
parsing code to recognize "auth_param ntlm" directives.

The problem does affect existing NTLM module, and may affect any future
module code as we reduce module's external footprint. This change
converts all RegisteredRunner registrations from using side effects of
static initialization to explicit registration calls from SquidMain().

Due to indeterminate C++ static initialization order, no module can
require registration before main() starts. Thus, moving registration
timing to the beginning of SquidMain() should have no negative effects.

The new registration API still does not expose main.cc to any module
details (other than the name of the registration function itself). We
still do not need to #include any module headers into main.cc. Compiler
or linker does catch most typos in RegisteredRunner names. TODO: Reject
duplicate registrations (at Squid startup time).

Unfortunately, explicit registration still cannot prevent bugs where we
forget to register a module or fail to register a module due to wrong
registration code guards. Eventually, CI will expose such bugs.