OT: Do not attempt to reforward pinned requests
... to better tolerate Ftp::Relay::sendCommand() and similar exceptions.

    ERROR: Squid BUG: assurance failed: ...
        exception location: FtpClient.cc(835) writeCommand
    AsyncJob.cc(145) callException: assurance failed ...
    AsyncJob.cc(100) mustStop: Ftp::Relay will stop, reason: exception
    ...
    FATAL: check failed: !request->pinnedConnection()
        exception location: FwdState.cc(1119) connectStart

When branch-added Ftp::Client::writeCommand() assertions throw, the
worker dies instead of just killing the affected ftp_port transaction.

`JobDialer::dial()` catches the BUG exception, as expected, but the
worker still dies because `Client::swanSong()` cleanup code calls
`FwdState::handleUnregisteredServerEnd()` which attempts to retry the
failed FTP transaction despite true `request->pinnedConnection()`, which
triggers another, this time uncaught, exception in `connectStart()`.

Also documented suspicions that `FwdState::pinnedCanRetry()` should
_always_ return false and, hence, should be removed (instead of adding
more and more code/conditions when that method returns false).

----

I hope this out-of-scope change can be reverted (and merged separately)
after we add CR protections to command parser and/or replace
writeCommand() assertions with (moved) embedded new line handling code.