WCCP: Fix GCC-10 -Wstringop-truncation failures
When building squid using GCC10, I'm seeing a few failures related to
the -Wstringop-truncation option:

In file included from /usr/include/string.h:495,
                 from ../compat/xstring.h:13,
                 from ../compat/compat_shared.h:225,
                 from ../compat/compat.h:87,
                 from ../include/squid.h:43,
                 from wccp2.cc:11:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘void wccp2_add_service_list(int, int, int, int, int, int*, int, char*)’ at wccp2.cc:523:12,
    inlined from ‘void parse_wccp2_service(void*)’ at wccp2.cc:2140:27:
/usr/include/s390x-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output may be truncated copying 8 bytes from a string of length 8 [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

The curious thing is that I can only trigger these failures when I
compile on s390x.

The fix here is simple and inspired by
02fc37ca9112cd2afd7d9f3acea06c53b900453a: use xstrncpy instead of
strncpy.  I confirmed that this fixes the problem by recompiling, and
doesn't introduce any other issues.

Signed-off-by: Sergio Durigan Junior <sergiodj@debian.org>