Fix support for squidconf directive parameter files (#2458) (#2459)
Those files were never found. 2022 commit d37a3744 probably missed this
bug because the corresponding `squid -k parse` failures (quoted below)
do not result in non-zero exit status code. That failure handling
problem deserves a dedicated fix.

    ERROR: Can not open file empty.conf for reading
        configuration context: ./squidconf/regressions-3.4.0.1.conf(27)

Co-authored-by: Alex Rousskov <rousskov@measurement-factory.com>