fixup: -Wconstexpr-not-const
    error: 'constexpr' non-static member function will not be implicitly
    'const' in C++1y; add 'const' to avoid a change in behavior

The constexpr profile was copied from the C++20 cppreference. It is
correct in C++20, but we should use the older/simpler profile to avoid
warnings about anticipated migration problems.