Fix ./configure eui check
1. Fix missing header `sys/socket.h`

```
configure:29217: checking for struct arpreq.arp_pa
.../net/if_arp.h:89:18: error: field has incomplete type 'struct sockaddr'
```

2. Fix ac_aggr.arp_pa test
```
conftest.cpp:112:5: error: value of type 'struct sockaddr' is not contextually convertible to 'bool'
```