Fix bad uses of OpenSSL 0.9 API
These ASN1_STRING_* API functions have been available
since OpenSSL 1.1, and Squid provides portability
wrappers for OpenSSL v1.0.

OpenSSL v4 removes struct asn1_string_st from public
availability. Leading to compile problem:

  error: invalid use of incomplete type ASN1_OCTET_STRING