Define MSG_DONTWAIT as MSG_NONBLOCK if needed and possible (#2477)
    fd.cc:138:56: error: 'MSG_DONTWAIT' was not declared in this scope;
    did you mean 'MSG_DONTROUTE'?

AIX does not define `MSG_DONTWAIT`. The functional equivalent of this
flag on AIX is `MSG_NONBLOCK`.

This change fixes `src/fd.cc` compilation on AIX, but more changes are
required to fix AIX build.