Fix builds using clang++
The build is aborted with the mesage:
 error: 'toCbdata' overrides a member function but is not marked 'override'

Use the CBDATA_CHILD instead of CBDATA_CLASS to declare cbdata  related
part in HappyConnOpener class.