Fixed gcc-8+ build error: undefined reference to __atomic_is_lock_free
Earlier compilers successfully processed the code generated by
AC_SEARCH_LIBS, producing a warning. In modern/more_strict
compilers (such as gcc-8), the warning became an error, resulting in
AC_SEARCH_LIBS failure when detecting libatomic.

Please see a related bug report for for detail:
   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907277#30

Ideally, this autoconf bug should be fixed first making AC_SEARCH_LIBS
usable again. However, it is unclear whether/when this is going to
happen. For now, I suggest another approach, utilizing AC_LINK_IFELSE
instead and the fact that calling atomic_lock_free() with a non-trivial
type requires linking against libatomic.