Various link errors in testDiskIO
TODO:
   Fix undefined reference to CommIO members
   discover whether any of the calls now stub'ed need to be used
   may need to pull CommIO out of comm.cc