Fix printing Security::ErrorDetail
Squid dumps RefCount pointer details instead of the intended TLS error
details like "SQUID_TLS_ERR_ACCEPT+TLS_LIB_ERR=14094418":

    ERROR: failure while accepting a TLS connection...: 0x564017165ef0*1

We overload operator << for ErrorDetail::Pointer to report errors, but
the compiler picks our operator << overload that prints any RefCount
pointer instead. I suspect this happens because the actual type of the
being-printed handshakeResult.errorDetail object (i.e.
Security::IoResult::ErrorDetailPointer) is not ErrorDetail::Pointer but
Security::ErrorDetail::Pointer; there is no overload for the latter.

We could overload operator << for Security::ErrorDetail::Pointer as
well, of course, but that would essentially duplicate code and, sooner
or later, another mismatching-operator bug like this will silently crop
up: Humans cannot reliably track such subtle dependencies, and our APIs
should be designed to prevent such conflicts at compile time instead.

This fix removes overloading "conflicts" (and reduces code duplication
while automatically covering more use cases) by removing specific
RefCount-derived overloads while making the base RefCount overload for
operator << smarter: If the underlying object type supports "printing"
with operator <<, then the base overload prints that object. This is
what our specific overloads for operator << tend do anyway!

XXX1: Given the two choices, some callers may want to print the address
and reference counts rather than the underlying object. This may include
existing callers that will now start printing the underlying objects. An
operator << overload for RefCount cannot know what (part of RefCount)
the caller really wants to print, and automatically printing the
underlying object may result in unexpected large object dumps.

XXX2: We removed existing overloading "conflicts", but we may
unknowingly add new ones. Aliasing makes it especially difficult to spot
code that overloads operator << for a RefCount-based pointer.

TODO: Avoid RawPointer() code duplication.