Fix Tokenizer::int64() parsing of "0" when guessing base
Known bug victims in current code were client_connection_mark and
(deprecated) clientside_mark ACLs if they were configured to match a
zero mark using "0/..." syntax:

    ERROR: configuration failure: NfMarkConfig: invalid value '0/10'...
    exception location: NfMarkConfig.cc(23) getNfmark

Probably broken since 2014 commit 01f2137d.