Support Nettle 4.0 md5_digest API (#2424)
    error: no matching function for call to nettle_md5_digest

Nettle v4.x md5_digest() function does not have a length parameter
present in Nettle v3.