fixup: #include the missing <algorithm> header
    compat/openssl.h:167:30: error: 'min' is not a member of 'std'

This old/unrelated bug was exposed by our #include order changes.