fixup: Fix incorrectly defaulted copy constructor and copy assignment
When one has a multi-member union and at least one of the members has a
non-trivial constructor or assignment operator, then no reasonable
default member-by-member implementation can be generated, and the
compiler rightfully complains:

    Optional.h:43:15: note: 'constexpr Optional<Value>::Optional(const
    Optional<Value>&) [with Value = C]' is implicitly deleted because
    the default definition would be ill-formed:

    Optional.h:98:15: error: union member 'Optional<C>::<unnamed
    union>::value_' with non-trivial 'C::C(const C&)'