ext_edirectory_userip_acl: strcat error
GCC 8 reports:
  error: strncat() accessing between 16393 and 8171 bytes at offsets
  16416 and 24 may overlap 1 byte at offset 16416 [-Werror=restrict]

Replace with single snprintf() instead of several catenations. That allows
us to use the result for a single bounds check instead of repeated tests.