Fix time_t type conflicts in libdebug (#1357)
    error: cannot convert 'const long int*' to 'const time_t*'

On Windows, time_t is 64-bit, and long is not.