Fix clang refresh.cc warning enabled by the (now restored) -Wall option
    src/refresh.cc:660:9: error: variable 'sum' set but not used
    [-Werror,-Wunused-but-set-variable]

The unused variable was left by commit a5ea775.