tools.cc: don't ignore return value of setuid()
Avoid a build error when cross-compiling for RISC-V Ubuntu 21.10:

tools.cc: In function ‘void enter_suid()’:
tools.cc:585:11: error: ignoring return value of ‘int setuid(__uid_t)’
declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  585 |     setuid(0);
      |     ~~~~~~^~~

When setuid() fails use similar debugs() like for setresuid() failure.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>