Fix regressions configuration
The regressions-3.4.0.1 configuration produces an error message:

    ERROR: Can not open file empty for reading

It became out-of-sync since 6c9a5e8, after renaming "empty" to
"empty.conf".